# my-role.yaml

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: my-role
  namespace: default
rules:
- apiGroups: ["", "apps", "extensions", "batch"]
  resources: ["deployments", "services"]
  verbs: ["create", "get", "list", "update", "delete", "patch"]

---

# my-role-binding.yaml

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: my-role-binding
  namespace: default
subjects:
- kind: Group
  name: my-group # Replace with the name of your group
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: my-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-deployment
  template:
    metadata:
      labels:
        app: server-deployment
    spec:
      nodeSelector: 
        kubernetes.io/hostname: e-ahned-pa2-vm2
      containers:
      - name: server-deployment
        image: etot/server-docker:0.1
        ports:
        - containerPort: 5000
        # env:
        # - name: COUCHDB_IP
        #   value: "129.114.26.125"

        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: server-entrypoint
  labels:
    app: server-deployment
spec:
  type: NodePort
  selector:
    app: server-deployment
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    nodePort: 30001