- categories:
  - food
- conversations:
  - - What are the serving for 2301 breakfast?
    - 'They are serving the following: smoothies, bowl'
  - - What are the serving for 2301 daily offerings?
    - 'They are serving the following: nuts, cracker'
